//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDev.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HRPO25E\\SQLEXPRESS;Initial Catalog=Client_Database;Integrated" +
            " Security=True;MultipleActiveResultSets=True")]
        public string Client_DatabaseConnectionString {
            get {
                return ((string)(this["Client_DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HRPO25E\\SQLEXPRESS;Initial Catalog=Purchase_OrderDB;Integrate" +
            "d Security=True;MultipleActiveResultSets=True")]
        public string Purchase_OrderDBConnectionString {
            get {
                return ((string)(this["Purchase_OrderDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HRPO25E\\SQLEXPRESS;Initial Catalog=RoleLogin;Integrated Secur" +
            "ity=True;MultipleActiveResultSets=True")]
        public string RoleLoginConnectionString {
            get {
                return ((string)(this["RoleLoginConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HRPO25E\\SQLEXPRESS;Initial Catalog=PurchaseInvoiceDB;Integrat" +
            "ed Security=True;MultipleActiveResultSets=True")]
        public string PurchaseInvoiceDBConnectionString {
            get {
                return ((string)(this["PurchaseInvoiceDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HRPO25E\\SQLEXPRESS;Initial Catalog=Sale_OrderDB;Integrated Se" +
            "curity=True;MultipleActiveResultSets=True")]
        public string Sale_OrderDBConnectionString {
            get {
                return ((string)(this["Sale_OrderDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HRPO25E\\SQLEXPRESS;Initial Catalog=SalesInvoice;Integrated Se" +
            "curity=True;MultipleActiveResultSets=True")]
        public string SalesInvoiceConnectionString {
            get {
                return ((string)(this["SalesInvoiceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HRPO25E\\SQLEXPRESS;Initial Catalog=Warehouse;Integrated Secur" +
            "ity=True;MultipleActiveResultSets=True")]
        public string WarehouseConnectionString {
            get {
                return ((string)(this["WarehouseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HRPO25E\\SQLEXPRESS;Initial Catalog=Accounts;Integrated Securi" +
            "ty=True;MultipleActiveResultSets=True")]
        public string AccountsConnectionString {
            get {
                return ((string)(this["AccountsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HRPO25E\\SQLEXPRESS;Initial Catalog=CompanyProfile;Integrated " +
            "Security=True;MultipleActiveResultSets=True")]
        public string CompanyProfileConnectionString {
            get {
                return ((string)(this["CompanyProfileConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HRPO25E\\SQLEXPRESS;Initial Catalog=LedgersOutstandings;Integr" +
            "ated Security=True")]
        public string LedgersOutstandingsConnectionString {
            get {
                return ((string)(this["LedgersOutstandingsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-HRPO25E\\SQLEXPRESS;Initial Catalog=FinancialYear;Integrated S" +
            "ecurity=True")]
        public string FinancialYearConnectionString {
            get {
                return ((string)(this["FinancialYearConnectionString"]));
            }
        }
    }
}
