//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareDev
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WarehouseEntity : DbContext
    {
        public WarehouseEntity()
            : base("name=WarehouseEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<getWarehouseReport_Result> getWarehouseReport(string color, string size, string quality)
        {
            var colorParameter = color != null ?
                new ObjectParameter("color", color) :
                new ObjectParameter("color", typeof(string));
    
            var sizeParameter = size != null ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(string));
    
            var qualityParameter = quality != null ?
                new ObjectParameter("quality", quality) :
                new ObjectParameter("quality", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getWarehouseReport_Result>("getWarehouseReport", colorParameter, sizeParameter, qualityParameter);
        }
    }
}
